app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),  # Главная.
    path('trainers', views.trainers, name='trainers'),  # Тренера.
    path('trainers/<int:pk>', views.trainer_detail, name='trainer_detail'),  # Карточка тренера.
    path('trainers/add_trainer', views.add_trainer, name='add_trainer'),  # Форма добавления тренера.
    path('trainers/delete_trainer/<int:pk>', views.delete_trainer, name='delete_trainer'),  # Удаление тренера.
    path('trainers/edit_trainer/<int:id>', views.edit_trainer, name='edit_trainer'),  # Форма редактирования тренера.
    path('schedules', views.show_schedules, name='show_schedules'),  # Расписание.
    path('schedules/add_schedule', views.add_schedule, name='add_schedule'),  # Форма добавления расписания.
    path('schedules/edit_schedule/<int:pk>', views.edit_schedule, name='edit_schedule'),  # Форма редактирования расписания.
    path('schedules/delete_schedule/<int:pk>', views.delete_schedule, name='delete_schedule'),  # Удаление расписания.
    path('development_and_design', views.development_and_design, name='development_and_design'),  # Разработка и дизайн.
    path('events', views.events, name='events'),  # Мероприятия.
    path('contacts', views.in_development, name='contacts'),  # Контакты.
    path('about', views.in_development, name='about'),  # О нас.
    path('sign_up', views.in_development, name='sign_up'),  # Записаться.
    path('achievements', views.in_development, name='achievements'),  # Достижения.
]

frb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # Админка.
    path('', include('app.urls')),  # Основное приложение.
    path('news', include('news.urls')),  # Новостное приложение.
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/add_trainer.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block css %}
    {% static 'css/app/trainer_add.style.css' %}
{% endblock %}

{% block content %}
    <main class="content">
        <div class="container">
            <div class="content__back"><a href="{% url 'app:trainers' %}">« Назад</a></div>
            <div class="content__title">Форма добавления тренера</div>
            <form action="{% url 'app:add_trainer' %}" method="post" class="content__form form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input style="display: block;" type="submit" value="Добавить" class="form__input-button">
            </form>
        </div>
    </main>
{% endblock content %}

app/templates/app/base.html
{% load static %}

{% load my_tags %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/null.style.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.style.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.style.css' %}">
    <link rel="stylesheet" href="{% static 'css/app/main.style.css' %}">
    <link rel="stylesheet" href="{% block css %} {% endblock css %}">
    <link type="image/x-icon" href="{% static 'img/fbr_logo.png' %}" rel="shortcut icon">
</head>
<body>
<div class="wrapper">
    {% include 'header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
</div>
<script src="{% static 'js/main.script.js' %}"></script>
</body>
</html>

app/templates/app/create_schedule.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="content">
        <div class="container">
            <h1 class="content__title">Редактирование</h1>
            <form action="{% url 'app:add_schedule' %}" method="post">
                {% csrf_token %}
                {{ form.days }}
                {{ form.time }}
                <button type="submit">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/app/development_and_design.html
{% extends 'app/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="content">
        <div class="container">
            <h2 class="content__developer developer">Разработка</h2>
            <div class="developer__card">
                <div class="developer__title">Вилигурин Виктор Николаевич</div>
                <div class="developer__info">
                    <div class="developer__tg">@tg_razrab</div>
                    <div class="developer__phone">+7 912 413-50-27</div>
                    <div class="developer__email">smt_razrab@mail.ru</div>
                </div>
            </div>
            <h2 class="content__design design">Дизайн</h2>
            <div class="design__card">
                <div class="design__title">Вилигурин Виктор Николаевич</div>
                <div class="design__info">
                    <div class="design__tg">@tg_razrab</div>
                    <div class="design__phone">+7 912 413-50-27</div>
                    <div class="design__email">smt_razrab@mail.ru</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/events.html
{% extends 'app/base.html' %}

{% load my_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="content">
        <div class="container">
            <h1 class="content__title">Мероприятия</h1>
            <div class="content__events">
                {% for event in events %}
                    <div class="content__event evnet">
                        <div class="evnet__image"><img src="" alt=""></div>
                        <div class="evnet__title">{{ event.title }}</div>
                        <div class="event__event-place">{{ event.event_place }}</div>
                        <div class="event__description">{{ event.description | cut:30 }}</div>
                        <a href="" class="event__detail">Подробнее</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% include 'app/navigation.html' %}
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block css %}{% static 'css/app/index.style.css' %}{% endblock css %}

{% block content %}
<main class="content">
    <div class="container">
        <div class="content__row">
            <div class="content__welcome ">
                <div class="content__title">ФРБ Нижневартовск</div>
                <div class="content__subtitle">
                    Добро пожаловать на сайт нашего клуба!
                </div>
                <div class="content__image">
                    <img src="{% static 'img/content_image.png' %}" alt="">
                </div>
            </div>
            {% include 'app/navigation.html' %}
        </div>
    </div>
</main>
{% endblock content %}

app/templates/app/navigation.html
<div class="content__nav nav">
    <div class="nav__title nav__title-1">Навигация</div>
    <nav class="nav__nav">
        <div><a href="{% url 'app:trainers' %}" class="nav__link">Наши тренера</a></div>
        <div><a href="{% url 'app:show_schedules' %}" class="nav__link">Расписание</a></div>
        <div><a href="{% url 'app:events' %}" class="nav__link">Мероприятия</a></div>
        <div><a href="{% url 'app:contacts' %}" class="nav__link">Контакты</a></div>
        <div><a href="{% url 'app:about' %}" class="nav__link">О нас</a></div>
    </nav>
</div>

app/templates/app/schedule_edit.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="content">
        <div class="container">
            <h1 class="content__title">Редактирование</h1>
            <form action="{% url 'app:edit_schedule' schedule.id %}" method="post">
                {% csrf_token %}
                {{ form.days }}
                {{ form.time }}
                <button type="submit">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/app/schedules.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="content">
        <div class="container">
            <h1 class="content__title">Расписание</h1>
            <a href="{% url 'app:add_schedule' %}" class="content__create"><img src="{% static 'img/add.png' %}" width="35" alt=""></a>
            <div class="content__schedules">
                {% for schedule in schedules %}
                    <h2 class="content__days">{{ schedule.days }}</h2>
                    {% for time in schedule.get_list %}
                        <p>{{ time }}</p>
                    {% endfor %}
                    <a href="{% url 'app:edit_schedule' schedule.id %}" class="content__edit"><img src="{% static 'img/free-icon-edit-3756597.png' %}" width="35" alt=""></a>
                    <a href="{% url 'app:delete_schedule' schedule.id %}" class="content__delete"><img src="{% static 'img/free-icon-bin-5661832.png' %}" width="35" alt=""></a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/trainer_detail.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block css %}{% static 'css/app/trainer_detail.style.css' %}{% endblock css %}

{% block content %}
    <main class="content">
        <div class="container">
            <div class="content__action-row">
                <div class="content__back"><a href="{% url 'app:trainers' %}">« Назад</a></div>
                {% if user.is_superuser or user.is_staff %}
                    <div class="content__delete"><a href="{% url 'app:delete_trainer' trainer.id %}">Удалить</a></div>
                    <div class="content__edit"><a href="{% url 'app:edit_trainer' trainer.id %}">Редактировать</a></div>
                {% endif %}
            </div>
            <div class="content__card card">
                <div class="card__body">
                    <div class="card__snp">{{ trainer.surname }} {{ trainer.name }} {{ trainer.patronymic }}</div>
                    <div class="card__education">Образование: {{ trainer.education }}</div>
                    <div class="card__experience">Опыт: {{ trainer.experience }} лет</div>
                </div>
                <div class="card__image">
                    <img oncontextmenu="return false" src="
                            {% if trainer.image %}{{ trainer.image.url }}{% else %}{% static 'img/default-avatar.png' %}{% endif %}"
                         alt="">
                </div>
            </div>
            <div class="content__description">Описание:<br><span>{{ trainer.description }}</span></div>
        </div>
    </main>
{% endblock content %}

app/templates/app/trainer_edit.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block css %}
    {% static 'css/app/trainer_edit.style.css' %}
{% endblock %}

{% block content %}
    <main class="content">
        <div class="container">
            <div class="content__back"><a href="{% url 'app:trainer_detail' trainer.id %}">« Назад</a></div>
            <div class="content__warning">При сохранении убедитесь, что фотография выбрана! Иначе будет
                загружена фотография по умолчанию!
            </div>
            <div class="content__title"></div>
            <form action="{% url 'app:edit_trainer' trainer.id %}" method="post" class="content__form form"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input class="form__input-button" style="display: block;" type="submit" value="Сохранить">
            </form>
        </div>
    </main>
{% endblock content %}

app/templates/app/trainers.html
{% extends 'app/base.html' %}

{% load static %}

{% load my_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block css %}{% static 'css/app/trainers.style.css' %}{% endblock css %}

{% block content %}
    <main class="content">
        <div class="container">
            <div class="content__title">Тренера</div>
            <a class="content__add" href="{% url 'app:add_trainer' %}">Добавить +</a>
            <div class="content__cards cards">
                <div class="cards__row">
                    {% for trainer in trainers %}
                        <div class="cards__card card">
                            <div class="card__image">
                                <img oncontextmenu="return false" src="{% if trainer.image %}{{ trainer.image.url }}{% else %}{% static 'img/default-avatar.png' %}{% endif %}" alt="">
                            </div>
                            <div class="card__title">
                                {{ trainer.surname }} {{ trainer.name|cut:1 }}.{% if trainer.patronymic %}
                                {{ trainer.patronymic|cut:1 }}.{% endif %}</div>
                            <div class="card__description">
                                {% if trainer.description|my_len > 150 %}{{ trainer.description|cut:150 }}...{% else %}{{ trainer.description }}{% endif %}
                            </div>
                            <div class="card__button"><a href="{% url 'app:trainer_detail' trainer.id %}">Подробнее...</a></div>
                        </div>
                    {% endfor %}

                </div>
            </div>
            {% if trainers.count > 6 %}
                <div class="content__pagination pagination">
                    <div class="pagination__row">
                        <a class="pagination__page" href="">Предыдущая</a>
                        <div><a class="pagination__page pagination__page-m" href="">1</a>
                            <a class="pagination__page pagination__page-m" href="">2</a>
                            <a class="pagination__page pagination__page-m" href="">3</a></div>
                        <a class="pagination__page pagination__page-next" href="">Следующая</a>
                    </div>
                </div>
            {% endif %}
            {% include 'app/navigation.html' %}
        </div>
    </main>
{% endblock %}