app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),  # Главная.
    path('trainers', views.trainers, name='trainers'),  # Тренера.
    path('trainers/<int:pk>', views.trainer_detail, name='trainer_detail'),  # Карточка тренера.
    path('trainers/add_trainer', views.add_trainer, name='add_trainer'),  # Форма добавления тренера.
    path('trainers/delete_trainer/<int:pk>', views.delete_trainer, name='delete_trainer'),  # Удаление тренера.
    path('trainers/edit_trainer/<int:id>', views.edit_trainer, name='edit_trainer'),  # Форма редактирования тренера.
    path('schedules', views.show_schedules, name='show_schedules'),  # Расписание.
    path('schedules/add_schedule', views.add_schedule, name='add_schedule'),  # Форма добавления расписания.
    path('schedules/edit_schedule/<int:pk>', views.edit_schedule, name='edit_schedule'),  # Форма редактирования расписания.
    path('schedules/delete_schedule/<int:pk>', views.delete_schedule, name='delete_schedule'),  # Удаление расписания.
    path('development_and_design', views.development_and_design, name='development_and_design'),  # Разработка и дизайн.
    path('events', views.events, name='events'),  # Мероприятия.
    path('contacts', views.in_development, name='contacts'),  # Контакты.
    path('about', views.in_development, name='about'),  # О нас.
    path('sign_up', views.in_development, name='sign_up'),  # Записаться.
    path('achievements', views.in_development, name='achievements'),  # Достижения.
]

frb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # Админка.
    path('', include('app.urls')),  # Основное приложение.
    path('news', include('news.urls')),  # Новостное приложение.
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from app import views as app_views

app_name = 'news'

urlpatterns = [
    path('', app_views.in_development, name='index'),  # Новости.
]

app/templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="footer__row">
            <div class="footer__link"><a style="cursor: pointer">© Авторские права защищены</a></div>
            <div class="footer__link"><a href="">Политика конфиденциальности</a></div>
            <div class="footer__link"><a href="{% url 'app:development_and_design' %}">Разработка и дизайн</a></div>
        </div>
    </div>
</footer>

app/templates/header.html
{% load static %}
{% load my_tags %}
<header class="header">
    <div class="container">
        <div class="header__row">
            <div class="header__logo">
                <a href="{% url 'app:index' %}"><img src="{% static 'img/fbr_logo.png' %}" alt=""></a>
            </div>
            <div class="header__menu menu">
                <div class="menu__icon">
                    <span></span>
                </div>
                <nav class="menu__body">
                    <a href="{% url 'news:index' %}" class="menu__link">Новости</a>
                    <a href="{% url 'app:achievements' %}" class="menu__link">Достижения</a>
                    {% if user.authenticated %}
                        <p class="menu__link profile">{{ user.last_name }} {{ user.first_name | cut:1 }}.</p>
                    {% endif %}
                    <a data-goto=".nav__title-1" href="" class="menu__link menu__navigation">Навигация</a>
                    <a href="{% url 'app:sign_up' %}" class="menu__link menu__button">Записаться</a>
                </nav>
            </div>
        </div>
    </div>
</header>

app/templates/in_development.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block css %}{% static 'css/in_development.style.css' %}{% endblock %}

{% block content %}
    <main class="content">
        <div class="container">
            <div class="content__message">
                <img src="{% static 'img/in_development.png' %}" alt="">
            </div>
            <div class="content__back">
                <a href="{% url 'app:index' %}" class="content__link">На главную</a>
            </div>
        </div>
    </main>
{% endblock %}